---
swagger: "2.0"
info:
  description: "I am playing a game"
  version: "0.0.1"
  title: "IAmPlayingAGame"
host: "virtserver.swaggerhub.com"
basePath: "/Zeavz9/PlayGame/0.0.1"
schemes:
- "https"
paths:
  /getscreen:
    get:
      summary: "ok"
      description: "ok"
      operationId: "getscreenGET"
      parameters: []
      responses:
        200:
          description: "OK"
          schema: {}
      x-swagger-router-controller: "Default"
definitions: {}
